### ISSUE TITLE
Some projects are archived

### ISSUE THREAD

**Issue by dveeden** [shlomi-noach/awesome-mysql#124]
At least these, and maybe more:
- [dbdeployer](https://github.com/datacharmer/dbdeployer)
- [Google Ripple](https://github.com/google/mysql-ripple)

Should we place a ` (archived)` or ` (unmaintained)` next to them? should we remove them?

**Comment by datacharmer** [comment]
Adding `(archived)` should be the right thing to do. At least for one year after the fact. There is always the chance that the project could be reopened.

**Comment by dveeden** [comment]
@MarkLeith what about `sys`? Should we keep it? remove it? add a note?

**Comment by shlomi-noach** [comment]
Wow, MHA is a voice from the past. @dveeden yes, update as specified please.
