### ISSUE TITLE
MariaDB4j

### ISSUE THREAD

**Issue by federico-razzoli** [shlomi-noach/awesome-mysql#136]
I'd like to propose this project:

https://github.com/MariaDB4j/MariaDB4j

I'm not making a PR because I'm not sure in which category it should be. I suppose Deployment is correct, but it could be a bit misleading because MariaDB4j is mostly for testing.

If you can advise on this, I'll be happy to make a PR.

**Comment by federico-razzoli** [comment]
Note that MariaDB is treated as an artifact, a package to launch. For this reason the license incompatibility is not a problem. If you have doubts, think about regular Linux package installers: they can install anything, regardless the license.

**Comment by shlomi-noach** [comment]
This looks really nice. I suggest creating a new `Libraries` section, though `Deployment` makes possibly more sense. Pick your preferred section and please open a PR.

**Comment by federico-razzoli** [comment]
I'll pick the Deployment option to avoid creating a category with one item. If more libraries are added, a category can always be created later.

**Comment by shlomi-noach** [comment]
Closed by #137
