### ISSUE TITLE
add kdbv ( mysql database auto schema migration library )

### ISSUE THREAD

**Issue by GaneshKandu** [shlomi-noach/awesome-mysql#62]
## Development

*Tools to support MySQL-related development*

- [kdbv](https://github.com/GaneshKandu/kdbv) - php based mysql database auto schema migration library.

**Comment by shlomi-noach** [comment]
@GaneshKandu if you feel `kbdv` answers the criteria defined in https://github.com/shlomi-noach/awesome-mysql/blob/gh-pages/CONTRIBUTING.md, please open a PR to add it.
