### ISSUE TITLE
Move list to README.md

### ISSUE THREAD

**Issue by stevestock** [shlomi-noach/awesome-mysql#63]
This is the **ONLY** [awesome](https://github.com/sindresorhus/awesome) project with the list somewhere other than `README.md`

are you open to moving the list?

**Comment by shlomi-noach** [comment]
I am. The list was originally in the `README.md` and for reasons outside the immediate logic of this repo, moved to `gh-pages`. I'm good to return to `README.md`.

**Comment by stevestock** [comment]
I think the gh-pages support is nice too. Some other repos have this as
well. Should be able to suppport both.

What was the outside reason?  I want to make sure I don’t mess anything up
if I make a PR

**Comment by shlomi-noach** [comment]
You will not be messing up anything. It's a legacy reason.

**Comment by shlomi-noach** [comment]
This was done!
