### ISSUE TITLE
Downloads are available at the Google Code openark kit project page

### ISSUE THREAD

**Issue by GETandSELECT** [shlomi-noach/awesome-mysql#67]
> openark kit - a set of utilities that solve everyday maintenance tasks, which may be complicated or time consuming to do by hand, written in Python.

it looks like openark kit is a not maintained project. Google Code shutdown many years ago.

Am I wrong?

P.S. thanks for great list

**Comment by dveeden** [comment]
Is this fixed by #121 ?

**Comment by shlomi-noach** [comment]
Closed by #121
