### ISSUE TITLE
Weekly MySQL News should be removed or replace

### ISSUE THREAD

**Issue by jonnycyr** [shlomi-noach/awesome-mysql#68]
The last issue of Weekly MySQL News was on 1/15/16 - it can be found here: https://us6.campaign-archive.com/?u=009fd87839a759e30570956a2&id=61b6bd7d29

I think that either the link should be removed, or it could be replaced with the [Vivid Cortex ](https://www.vividcortex.com/newsletter-sign-up) newsletter. In the last issue the creators state that the content will be moving over to Vivid Cortex. It seems that Vivid Cortex does not focus solely on MySQL. I've signed up for the newsletter to check it out. If it seems good, I'll create a PR to add it to the list.

**Comment by shlomi-noach** [comment]
Sorry for the late response. The Weekly newsletter has been removed!
