### ISSUE TITLE
Add dbForge Studio for MySQL to "GUI"

### ISSUE THREAD

**Issue by JordanS22** [shlomi-noach/awesome-mysql#70]
[dbForge Studio for MySQL](https://www.devart.com/dbforge/mysql/studio/features.html) - a universal GUI tool for MySQL and MariaDB database development, management, and administration.

**Comment by JordanS22** [comment]
There is a free dbForge Studio for MySQL Express Edition at 
https://www.devart.com/dbforge/mysql/studio/editions.html

**Comment by shlomi-noach** [comment]
> Must be free and open source. Must have an acknowledged open source license.

@JordanS22 these are the terms for this curated list.

**Comment by shlomi-noach** [comment]
Your contribution is much appreciated. There is nothing wrong with commercial or closed source products, and the tool may be of value to the user. However, this list only curates free and open source resources, and dbForge does not meet the criteria.
Thank you.

**Comment by JordanS22** [comment]
Thank you for the reply. Unfortunately, i saw other commercial products from our competitors there, so i thought that free edition meets the requirements. Sorry for the inconvenience.

**Comment by shlomi-noach** [comment]
@JordanS22 can you please point me to an entry that is not free & open source? If there is one, I'll remove it.
